seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 10000
empirical_normalization: true
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
algorithm:
  class_name: AMPPPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.005
  desired_kl: 0.01
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  amp_replay_buffer_size: 100000
clip_actions: null
save_interval: 500
experiment_name: asimov_velocity_amp
run_name: amp
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
runner_type: rsl_rl_amp.runners.amp_on_policy_runner:AMPOnPolicyRunner
amp_data:
  class_type: beyondAMP.motion.motion_dataset:MotionDataset
  asset_name: robot
  motion_files:
  - /home/menlo/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/manager_based/locomotion/velocity/config/asimov_1/motions/policy_delay_walk_slow.npz
  joint_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - waist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_yaw_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_yaw_joint
  body_names:
  - left_ankle_roll_link
  - right_ankle_roll_link
  - left_wrist_yaw_link
  - right_wrist_yaw_link
  - waist_yaw_link
  amp_obs_terms:
  - joint_pos
  - joint_vel
  anchor_name: pelvis_link
amp_reward_coef: 0.3
amp_discr_hidden_dims:
- 256
- 256
amp_task_reward_lerp: 0.7
amp_min_normalized_std: 0.0
amp_reward_command_gate: true
amp_reward_command_name: twist
amp_reward_command_threshold: 0.1
